/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all products
         * @description Retrieve a paginated list of products with optional filtering
         */
        get: {
            parameters: {
                query?: {
                    /**
                     * @description Filter by category slug
                     * @example laptops
                     */
                    category?: string;
                    /**
                     * @description Minimum price filter
                     * @example 100
                     */
                    minPrice?: number;
                    /**
                     * @description Maximum price filter
                     * @example 2000
                     */
                    maxPrice?: number;
                    /**
                     * @description Search in name, description, SKU
                     * @example macbook
                     */
                    search?: string;
                    /** @description Number of results per page */
                    limit?: number;
                    /** @description Pagination offset */
                    offset?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Product"][];
                            pagination?: components["schemas"]["Pagination"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get product by slug */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @example macbook-pro-16-m3-max */
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Product found */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Product"];
                        };
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all categories */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Category"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get category with products */
        get: {
            parameters: {
                query?: {
                    limit?: number;
                    offset?: number;
                };
                header?: never;
                path: {
                    /** @example laptops */
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Category with products */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["CategoryWithProducts"];
                            pagination?: components["schemas"]["Pagination"];
                        };
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create new cart */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: int64 */
                        userId?: number;
                        sessionId?: string;
                    } & (unknown | unknown);
                };
            };
            responses: {
                /** @description Cart created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Cart"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cart/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get cart with items */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Cart token (UUID) */
                    token: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Cart with items */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["CartWithItems"];
                        };
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cart/{token}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add item to cart */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Cart token (UUID) */
                    token: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * @description Product slug (preferred)
                         * @example macbook-pro-16-m3-max
                         */
                        productSlug?: string;
                        /**
                         * Format: int64
                         * @description Product ID (backward compatibility)
                         */
                        productId?: number;
                        /** @default 1 */
                        quantity?: number;
                    } & (unknown | unknown);
                };
            };
            responses: {
                /** @description Item added to cart */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["CartWithItems"];
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cart/{token}/items/{itemId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update item quantity */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Cart token (UUID) */
                    token: string;
                    itemId: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        quantity: number;
                    };
                };
            };
            responses: {
                /** @description Item updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["CartWithItems"];
                        };
                    };
                };
            };
        };
        post?: never;
        /** Remove item from cart */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Cart token (UUID) */
                    token: string;
                    itemId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Item removed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message?: string;
                            data?: components["schemas"]["CartWithItems"];
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create order from cart
         * @description Convert cart to order, validate stock, and update inventory atomically
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * Format: uuid
                         * @description Cart token from cart creation
                         */
                        cartToken: string;
                        /** Format: int64 */
                        userId?: number;
                        shippingAddress: components["schemas"]["Address"];
                        billingAddress?: components["schemas"]["Address"];
                    };
                };
            };
            responses: {
                /** @description Order created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Order"];
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{orderNumber}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get order details */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description Human-readable order number
                     * @example ORD-2024-000001
                     */
                    orderNumber: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Order details */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["OrderWithItems"];
                        };
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register new user */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: email */
                        email: string;
                        password: string;
                        firstName: string;
                        lastName: string;
                    };
                };
            };
            responses: {
                /** @description User registered */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthResponse"];
                    };
                };
                /** @description User already exists */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login user */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: email */
                        email: string;
                        password: string;
                    };
                };
            };
            responses: {
                /** @description Login successful */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthResponse"];
                    };
                };
                /** @description Invalid credentials */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Product: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            category_id?: number | null;
            name?: string;
            slug?: string;
            description?: string;
            /** Format: decimal */
            price?: number;
            /** Format: decimal */
            compare_at_price?: number;
            sku?: string;
            stock_quantity?: number;
            images?: string[];
            specifications?: Record<string, never>;
            is_active?: boolean;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
            category_name?: string;
            category_slug?: string;
        };
        Category: {
            /** Format: int64 */
            id?: number;
            name?: string;
            slug?: string;
            description?: string;
            /** Format: int64 */
            parent_id?: number | null;
            /** Format: uri */
            image_url?: string;
            product_count?: number;
            /** Format: date-time */
            created_at?: string;
        };
        CategoryWithProducts: components["schemas"]["Category"] & {
            products?: components["schemas"]["Product"][];
        };
        Cart: {
            /** Format: int64 */
            id?: number;
            /**
             * Format: uuid
             * @description Secure token for cart access
             */
            cart_token?: string;
            /** Format: int64 */
            user_id?: number | null;
            session_id?: string | null;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        CartItem: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            cart_id?: number;
            /** Format: int64 */
            product_id?: number;
            quantity?: number;
            /** Format: decimal */
            price?: number;
            /** Format: date-time */
            created_at?: string;
        };
        CartWithItems: components["schemas"]["Cart"] & {
            items?: (components["schemas"]["CartItem"] & {
                product_name?: string;
                product_images?: string[];
                product_slug?: string;
                stock_quantity?: number;
                subtotal?: number;
            })[];
            subtotal?: number;
            tax?: number;
            total?: number;
        };
        Order: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            user_id?: number | null;
            /**
             * @description Human-readable order identifier
             * @example ORD-2024-000001
             */
            order_number?: string;
            /** @enum {string} */
            status?: "pending" | "processing" | "shipped" | "delivered" | "cancelled";
            subtotal?: number;
            tax?: number;
            shipping?: number;
            total?: number;
            shipping_address?: components["schemas"]["Address"];
            billing_address?: components["schemas"]["Address"];
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        OrderItem: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            order_id?: number;
            /** Format: int64 */
            product_id?: number | null;
            product_name?: string;
            product_sku?: string;
            quantity?: number;
            price?: number;
            total?: number;
            /** Format: date-time */
            created_at?: string;
        };
        OrderWithItems: components["schemas"]["Order"] & {
            items?: components["schemas"]["OrderItem"][];
        };
        Address: {
            name: string;
            street: string;
            city: string;
            state: string;
            zip: string;
            country: string;
        };
        SavedAddress: {
            id: number;
            userId: number;
            type?: string;
            firstName?: string;
            lastName?: string;
            addressLine1: string;
            addressLine2?: string;
            city: string;
            state?: string;
            postalCode: string;
            country: string;
            phoneNumber?: string;
            isDefault: boolean;
            createdAt: string;
            updatedAt: string;
        };
        User: {
            /** Format: int64 */
            id?: number;
            /**
             * Format: uuid
             * @description External UUID for secure references
             */
            uuid?: string;
            /** Format: email */
            email?: string;
            first_name?: string;
            last_name?: string;
            /** @enum {string} */
            role?: "customer" | "admin";
            /** Format: date-time */
            created_at?: string;
        };
        AuthResponse: {
            message?: string;
            data?: {
                user?: components["schemas"]["User"];
                /** @description JWT token */
                token?: string;
            };
        };
        Pagination: {
            total?: number;
            limit?: number;
            offset?: number;
            hasMore?: boolean;
        };
        Error: {
            error?: string;
            message?: string;
            details?: Record<string, never>[];
        };
    };
    responses: {
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Bad request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Unauthorized */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
