// Orders API Routes
// POST /api/orders - Create order from cart (accepts cartToken)
// GET /api/orders/:orderNumber - Get order details by order number

const express = require('express');
const router = express.Router();
const db = require('../config/database');

// POST /api/orders - Create order from cart
router.post('/', async (req, res, next) => {
    const client = await db.getClient();

    try {
        const {
            cartToken,
            userId,
            shippingAddress,
            billingAddress,
        } = req.body;

        if (!cartToken || !shippingAddress) {
            return res.status(400).json({
                error: 'Bad Request',
                message: 'cartToken and shippingAddress are required',
            });
        }

        await client.query('BEGIN');

        // Get cart ID from cart_token
        const cartQuery = 'SELECT id FROM carts WHERE cart_token = $1';
        const cartResult = await client.query(cartQuery, [cartToken]);

        if (cartResult.rows.length === 0) {
            await client.query('ROLLBACK');
            return res.status(404).json({
                error: 'Not Found',
                message: 'Cart not found',
            });
        }

        const cartId = cartResult.rows[0].id;

        // Get cart items
        const cartItemsQuery = `
      SELECT 
        ci.*,
        p.name as product_name,
        p.sku as product_sku,
        p.stock_quantity
      FROM cart_items ci
      JOIN products p ON ci.product_id = p.id
      WHERE ci.cart_id = $1
    `;
        const cartItems = await client.query(cartItemsQuery, [cartId]);

        if (cartItems.rows.length === 0) {
            await client.query('ROLLBACK');
            return res.status(400).json({
                error: 'Bad Request',
                message: 'Cart is empty',
            });
        }

        // Check stock availability for all items
        for (const item of cartItems.rows) {
            if (item.stock_quantity < item.quantity) {
                await client.query('ROLLBACK');
                return res.status(400).json({
                    error: 'Insufficient Stock',
                    message: `${item.product_name} has insufficient stock`,
                });
            }
        }

        // Calculate totals
        const subtotal = cartItems.rows.reduce(
            (sum, item) => sum + item.quantity * parseFloat(item.price),
            0
        );
        const tax = subtotal * 0.1; // 10% tax
        const shipping = 0; // Free shipping for MVP
        const total = subtotal + tax + shipping;

        // Create order (order_number is auto-generated by trigger)
        const createOrderQuery = `
      INSERT INTO orders (
        user_id, status, subtotal, tax, shipping, total,
        shipping_address, billing_address
      )
      VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
      RETURNING *
    `;
        const orderResult = await client.query(createOrderQuery, [
            userId || null,
            'pending',
            subtotal,
            tax,
            shipping,
            total,
            JSON.stringify(shippingAddress),
            billingAddress ? JSON.stringify(billingAddress) : null,
        ]);

        const order = orderResult.rows[0];

        // Create order items and update stock
        for (const item of cartItems.rows) {
            // Insert order item
            const orderItemQuery = `
        INSERT INTO order_items (
          order_id, product_id, product_name, product_sku,
          quantity, price, total
        )
        VALUES ($1, $2, $3, $4, $5, $6, $7)
      `;
            await client.query(orderItemQuery, [
                order.id,
                item.product_id,
                item.product_name,
                item.product_sku,
                item.quantity,
                item.price,
                item.quantity * parseFloat(item.price),
            ]);

            // Update product stock
            const updateStockQuery = `
        UPDATE products
        SET stock_quantity = stock_quantity - $1
        WHERE id = $2
      `;
            await client.query(updateStockQuery, [item.quantity, item.product_id]);
        }

        // Clear cart
        const clearCartQuery = 'DELETE FROM cart_items WHERE cart_id = $1';
        await client.query(clearCartQuery, [cartId]);

        await client.query('COMMIT');

        res.status(201).json({ data: order });
    } catch (error) {
        await client.query('ROLLBACK');
        next(error);
    } finally {
        client.release();
    }
});

// GET /api/orders/:orderNumber - Get order details by order number
router.get('/:orderNumber', async (req, res, next) => {
    try {
        const { orderNumber } = req.params;

        // Get order by order_number
        const orderQuery = 'SELECT * FROM orders WHERE order_number = $1';
        const orderResult = await db.query(orderQuery, [orderNumber]);

        if (orderResult.rows.length === 0) {
            return res.status(404).json({
                error: 'Not Found',
                message: 'Order not found',
            });
        }

        const order = orderResult.rows[0];

        // Get order items
        const itemsQuery = `
      SELECT * FROM order_items
      WHERE order_id = $1
    `;
        const itemsResult = await db.query(itemsQuery, [order.id]);

        res.json({
            data: {
                ...order,
                items: itemsResult.rows,
            },
        });
    } catch (error) {
        next(error);
    }
});

// GET /api/orders - Get user orders
router.get('/', async (req, res, next) => {
    try {
        const { userId } = req.query;

        if (!userId) {
            return res.status(400).json({
                error: 'Bad Request',
                message: 'userId query parameter is required'
            });
        }

        const query = `
            SELECT * FROM orders
            WHERE user_id = $1
            ORDER BY created_at DESC
        `;
        const result = await db.query(query, [userId]);

        res.json({
            data: result.rows
        });
    } catch (error) {
        next(error);
    }
});

module.exports = router;
